### ISSUE TITLE
PSR-7 compatibility

### ISSUE THREAD

**Issue by lunetics** [Speicher210/fastbill-bundle#2]
Wouldn't it be nice to have a psr-7 compliant transport?

Ended up doing my own transport based off csa guzzle bundle. ( to have profiler debug in sf2)

**Comment by dragosprotung** [comment]
The transport is in the fastbill api package that uses Guzzle, but I would create a DataCollector specifically for this bundle in order to have the functionality independent of the transport that is used.

**Comment by lunetics** [comment]
Wouldn't it be better to seperate these concerns? So PSR-7 and the end-user chooses which psr-7 implementation he wants to use (e.g. with his own middleware in guzzle for example)
But I also think that an additional DataCollector can't hurt :)

And thanks for this bundle, saves me some headaches :) I want to invite you to our service for free once it's finished :)

**Comment by dragosprotung** [comment]
it would be better to have PSR-7 support. Unfortunately I do not have any immediate use for it, but I could help out on refactoring if you want to pitch in.

**Comment by lunetics** [comment]
Sure :)

For now our product launch has priority, but I will keep you posted :+1:

**Comment by dragosprotung** [comment]
happy coding :+1:
